groups_to_enable_for:
  type: list
  default: ""
  description: 
    en: "User groups to enable this component for. Case sensitive. Trust Levels can be used.  Group visibilty settings must be set everyone. Leave blank for all groups."
  
categories_to_disable_for:
  type: list
  default: ""
  description: 
    en: "Categories to disable for this component for. Use loweer case category slugs, separate sub-categories with a dash (ie: category-subcategory, lounge-vip). Leave blank to enable for all categories."
